// import {addDoc, collection} from "firebase/firestore"; 
// import {db} from "../config/firebaseConfig";

// const products = [
//     {
//     name:"Remera 01", 
//     img:"url-image", 
//     price:5000, 
//     category:"ropa", 
//     description:"remera-01", 
//     stock:25,
// },
//     {
//     name:"Remera 02", 
//     img:"url-image", 
//     price:6000, 
//     category:"ropa", 
//     description:"remera-02", 
//     stock:25,
// },
//     {
//     name:"Remera 03", 
//     img:"url-image", 
//     price:6500, 
//     category:"ropa", 
//     description:"remera-03", 
//     stock:25,
// },
//     {
//     name:"Remera 04", 
//     img:"url-image", 
//     price:6800, 
//     category:"ropa", 
//     description:"remera-04", 
//     stock:25,
// },
//     {
//     name:"Bermuda 01", 
//     img:"url-image", 
//     price:9000, 
//     category:"ropa", 
//     description:"bermuda-01", 
//     stock:25,
// },
//     {
//     name:"Bermuda 02", 
//     img:"url-image", 
//     price:9200, 
//     category:"ropa", 
//     description:"bermuda-02", 
//     stock:25,
// },
//     {
//     name:"Bermuda 03", 
//     img:"url-image", 
//     price:10300, 
//     category:"ropa", 
//     description:"bermuda-03", 
//     stock:25,
// },
//     {
//     name:"Bermuda 04", 
//     img:"url-image", 
//     price:11000, 
//     category:"ropa", 
//     description:"bermuda-04", 
//     stock:25,
// },
//     {
//     name:"Short 01", 
//     img:"url-image", 
//     price:7200, 
//     category:"ropa", 
//     description:"short-01", 
//     stock:25,
// },
//     {
//     name:"Short 02", 
//     img:"url-image", 
//     price:7450, 
//     category:"ropa", 
//     description:"short-02", 
//     stock:25,
// },
//     {
//     name:"Short 03", 
//     img:"url-image", 
//     price:8600, 
//     category:"ropa", 
//     description:"short-03", 
//     stock:25,
// },
//     {
//     name:"Short 04", 
//     img:"url-image", 
//     price:7800, 
//     category:"ropa", 
//     description:"short-04", 
//     stock:25,
// },
//     {
//     name:"Camiseta 01", 
//     img:"url-image", 
//     price:11000, 
//     category:"ropa", 
//     description:"camiseta-01", 
//     stock:25,
// },
//     {
//     name:"Camiseta 02", 
//     img:"url-image", 
//     price:10000, 
//     category:"ropa", 
//     description:"camiseta-02", 
//     stock:25,
// },
//     {
//     name:"Camiseta 03", 
//     img:"url-image", 
//     price:10000, 
//     category:"ropa", 
//     description:"camiseta-03", 
//     stock:25,
// },
//     {
//     name:"Camiseta 04", 
//     img:"url-image", 
//     price:10000, 
//     category:"ropa", 
//     description:"camiseta-04", 
//     stock:25,
// },
//     {
//     name:"Zapatilla 01", 
//     img:"url-image", 
//     price:20000, 
//     category:"calzados", 
//     description:"zapatilla-01", 
//     stock:25,
// },
//     {
//     name:"Zapatilla 02", 
//     img:"url-image", 
//     price:25000, 
//     category:"calzados", 
//     description:"zapatilla-02", 
//     stock:25,
// },
//     {
//     name:"Zapatilla 03", 
//     img:"url-image", 
//     price:30000, 
//     category:"calzados", 
//     description:"zapatilla-03", 
//     stock:25,
// },
//     {
//     name:"Zapatilla 04", 
//     img:"url-image", 
//     price:35000, 
//     category:"calzados", 
//     description:"zapatilla-04", 
//     stock:25,
// },
//     {
//     name:"Medias 01", 
//     img:"url-image", 
//     price:2500, 
//     category:"calzados", 
//     description:"medias-01", 
//     stock:25,
// },
//     {
//     name:"Medias 02", 
//     img:"url-image", 
//     price:3000, 
//     category:"calzados", 
//     description:"medias-02", 
//     stock:25,
// },
//     {
//     name:"Medias 03", 
//     img:"url-image", 
//     price:3000, 
//     category:"calzados", 
//     description:"medias-03", 
//     stock:25,
// },
//     {
//     name:"Medias 04", 
//     img:"url-image", 
//     price:3700, 
//     category:"calzados", 
//     description:"medias-04", 
//     stock:25,
// },
//     {
//     name:"Pantalón 01", 
//     img:"url-image", 
//     price:14000, 
//     category:"ropa", 
//     description:"pantalon-01", 
//     stock:25,
// },
//     {
//     name:"Pantalón 02", 
//     img:"url-image", 
//     price:15000, 
//     category:"ropa", 
//     description:"pantalon-02", 
//     stock:25,
// },
//     {
//     name:"Pantalón 03", 
//     img:"url-image", 
//     price:16000, 
//     category:"ropa", 
//     description:"pantalon-03", 
//     stock:25,
// },
//     {
//     name:"Pantalón 04", 
//     img:"url-image", 
//     price:17000, 
//     category:"ropa", 
//     description:"pantalon-04", 
//     stock:25,
// },
//     {
//     name:"Ojotas 01", 
//     img:"url-image", 
//     price:6000, 
//     category:"calzados", 
//     description:"ojotas-01", 
//     stock:25,
// },
// ];

// export const seedProducts = () => {
//     products.forEach(product=> {
//         addDoc(collection(db, "products"), product)
//     });
// };